### ISSUE TITLE
fetching a map by ID returns the wrong difficulty

### ISSUE THREAD

**Issue by AndrewwwGoodwin** [Tunnelbliick/qunav2#9]
![image](https://user-images.githubusercontent.com/9783984/196785070-1bc5dbdb-92f1-4e82-a8f2-126e2064b82d.png)
![image](https://user-images.githubusercontent.com/9783984/196785100-e803c6b4-14fb-42fc-8d0b-a5d3dfe6f54b.png)

calling a map by id only returns the top diff of the set

https://osu.ppy.sh/beatmapsets/807850#osu/1695382
https://osu.ppy.sh/beatmapsets/807850#osu/1700527

**Comment by Tunnelbliick** [comment]
fixed
